### ISSUE TITLE
Transfer this repo to maintainer account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/miner#24]
:wave: @kbroman! Would you like to transfer this repository and https://github.com/ropenscilabs/miner_book to your own account? Cf our [curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages).

**Comment by kbroman** [comment]
Sure, you can transfer them to me. Also [craft](https://github.com/ropenscilabs/craft).

**Comment by maelle** [comment]
Ok, I'll do that right now. Note that because the repos currently live in an organization, I'll follow the clunky workflow of transferring them to my account then yours.

**Comment by maelle** [comment]
@kbroman can you please remove your fork of craft? I can't transfer the repo to you because you already have a fork of it, sorry.

**Comment by maelle** [comment]
Same with miner and miner_book

**Comment by kbroman** [comment]
okay; all deleted.

**Comment by kbroman** [comment]
they were forked at the beginning of development, in 2017 I think.

**Comment by maelle** [comment]
aaah ok. I thought I had checked there was no fork before I made the transfer but I think I stupidly looked in your source repos (the default view when one uses RefinedGitHub) :woman_facepalming: Thanks for your patience.

**Comment by kbroman** [comment]
Hi, @geanders @daroczig @inchiosa @revodavid @akzaidi, wanted to let you know that the miner and craft packages have been moved off [ropenscilabs](https://github.com/ropenscilabs), to [kbroman](https://kbroman.org), and the miner book was moved to <https://kbroman.org/miner_book>.

**Comment by geanders** [comment]
Thanks for the update, @kbroman. Sounds great!
